on: [push]

jobs:
  test_vs_publisher:
    runs-on: windows-latest
    name: A job to test VSIX Version
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test Publisher
      uses: ./
      with:
        version: 1.5.7  
        vsix-manifest-file: samples\source.extension.vsixmanifest
    - name: Inspect content
      run: Get-Content samples\source.extension.vsixmanifest -Raw    